sudo: false

language: python
python:
  - "2.7"

env:
  - TEST_DIR=tests

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests $TEST_DIR

notifications:
  email:
    - lindseyheagy@gmail.com
